// <auto-generated />
namespace AdobeLicenseManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangededTagnumbersbacktointstotestrangedataannotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangededTagnumbersbacktointstotestrangedataannotation));
        
        string IMigrationMetadata.Id
        {
            get { return "201704242136106_Changeded Tag numbers back to ints to test range dataannotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
