// <auto-generated />
namespace AdobeLicenseManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RemovelengthlimitonSavedQueriesDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovelengthlimitonSavedQueriesDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201705102202314_Remove length limit on SavedQueries Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
